#!/usr/bin/env bash
#
# Air cloud environment setup for compose-multiplatform-core.
# Runs on every environment launch - the snapshotted warmup and each task start - so it is idempotent.
#
# Installs a JDK 21 and the Android SDK, then points Gradle at them.
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"

# The image ships only JBR 25; the repository's convention, and CI, is JDK 21.
JDK_DIR="$HOME/.local/jdk-21"
JDK_URL="https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%2B11/OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz"

SDK_DIR="$HOME/android-sdk"
# dl.google.com is blocked by the proxy; the JetBrains redirector mirrors it.
SDK_MIRROR="https://cache-redirector.jetbrains.com/dl.google.com/android/repository/"
# 34/36 from gradle.properties, 35 from per-module compileSdk, build-tools from AndroidXConfig.kt.
SDK_PACKAGES=(
  platform-tools
  'platforms;android-34' 'platforms;android-35' 'platforms;android-36'
  'build-tools;36.0.0'
)

log() { printf '[startup] %s\n' "$*"; }

install_jdk() {
  if [ -x "$JDK_DIR/bin/javac" ]; then
    log "JDK 21 already installed"
    return
  fi
  log "installing JDK 21"
  mkdir -p "$JDK_DIR"
  curl -fL --retry 3 --retry-all-errors -o /tmp/jdk21.tar.gz "$JDK_URL"
  tar xzf /tmp/jdk21.tar.gz -C "$JDK_DIR" --strip-components=1
  rm -f /tmp/jdk21.tar.gz
}

# JAVA_HOME: sdkmanager is a Java program. SDK_TEST_BASE_URL: only way to redirect its downloads.
run_sdkmanager() {
  JAVA_HOME="$JDK_DIR" SDK_TEST_BASE_URL="$SDK_MIRROR" \
    "$SDK_DIR/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK_DIR" "$@"
}

# All packages, so a half-finished install is not mistaken for a complete one.
# Package id maps to its directory: 'platforms;android-34' -> platforms/android-34.
sdk_is_complete() {
  local pkg
  for pkg in "${SDK_PACKAGES[@]}"; do
    [ -d "$SDK_DIR/${pkg//;//}" ] || return 1
  done
}

install_sdk() {
  # The androidx plugin aborts configuration when it finds no SDK.
  if sdk_is_complete; then
    log "Android SDK already installed"
    return
  fi
  log "installing the Android SDK"
  rm -rf /tmp/sdk-tools "$SDK_DIR/cmdline-tools/latest"
  mkdir -p "$SDK_DIR/cmdline-tools"
  curl -fL --retry 3 --retry-all-errors -o /tmp/sdk-tools.zip \
    "${SDK_MIRROR}commandlinetools-linux-11076708_latest.zip"
  # No unzip in the image; python3's zipfile drops the executable bit.
  python3 -m zipfile -e /tmp/sdk-tools.zip /tmp/sdk-tools
  mv /tmp/sdk-tools/cmdline-tools "$SDK_DIR/cmdline-tools/latest"
  chmod +x "$SDK_DIR/cmdline-tools/latest/bin"/*
  rm -rf /tmp/sdk-tools.zip /tmp/sdk-tools

  # Licences first; `yes` then dies of SIGPIPE, which pipefail would report as a failure.
  yes 2>/dev/null | run_sdkmanager --licenses >/dev/null || true
  run_sdkmanager "${SDK_PACKAGES[@]}"
}

write_gradle_config() {
  # Overrides the repository's 12 GB + 8 GB daemons, too big for this 15 GB / 4 CPU container.
  # installations.paths stands in for fromEnv=ANDROIDX_JDK21, unset here, with auto-detect off.
  mkdir -p "$HOME/.gradle"
  cat > "$HOME/.gradle/gradle.properties" <<EOF
# Generated by .air/cloud/startup.sh on every launch - do not edit.
org.gradle.java.home=$JDK_DIR
org.gradle.java.installations.paths=$JDK_DIR
org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -Dkotlin.daemon.jvm.options=-XX:MaxMetaspaceSize=1g,-Xmx5g -Dlint.nullness.ignore-deprecated=true -Dfile.encoding=UTF-8
org.gradle.workers.max=3
EOF

  # registry.yarnpkg.com is unreachable from Air; Yarn 1 honors this user-level setting.
  cat > "$HOME/.yarnrc" <<EOF
# Generated by .air/cloud/startup.sh on every launch - do not edit.
registry "https://registry.npmjs.org"
EOF

  # sdk.dir outranks $ANDROID_HOME, so the shell environment stays untouched.
  cat > "$REPO_DIR/local.properties" <<EOF
# Generated by .air/cloud/startup.sh on every launch - do not edit.
sdk.dir=$SDK_DIR
EOF
  log "wrote Gradle, Yarn, and local.properties configuration"
}

install_jdk
install_sdk
write_gradle_config
log "ready"
